### ISSUE TITLE
How Can I receive LoRa Data?

### ISSUE THREAD

**Issue by paengpd** [kriswiner/CMWX1ZZABZ#19]
Do you have Example code?
TX is so good.
but RX is not good.

I use below code.
but can't enter.

int packetSize = LoRaWAN.parsePacket();
{
}

Any ideas?

**Comment by kriswiner** [comment]
Try the LoRaWAN_Callbacks example for Grasshopper.

**Comment by paengpd** [comment]
I want use only two grasshopper.
If one grasshopper did Join request, other grasshopper have to Join accept.
But I can't find Join accept example.
Do I must use geteway or network server?
Grasshopper can't do that?

**Comment by kriswiner** [comment]
No, you can use LoRa Radio or FSK examples, check for ping_pong example,
then no gateway required.

**Comment by paengpd** [comment]
I did it for use Radio example.
but I want receive data for use LoRaWAN.
Can you tell me good idea?

**Comment by kriswiner** [comment]
For LoRaWAN you need a gateway.
