### ISSUE TITLE
Gnat questions

### ISSUE THREAD

**Issue by nobodyguy** [kriswiner/CMWX1ZZABZ#8]
Hi, thank you for your amazing work! I have 2 questions about Gnat board.

1. Do you sell the board? I couldn't find it on Tindie.
2. Do you have the schematic of the board?

Thank you.

**Comment by kriswiner** [comment]
Gnat will be available in January from Tindie.

The design is not open source (Grasshopper development board is though) but
I will likely post a schematic on the Tindie page.

**Comment by nobodyguy** [comment]
Great, thanks a lot for the info.
